version: '3'
services:
  chatwithuser:
    build:
      context: ./chatuser/
      dockerfile: ./macro_buffer/Dockerfile
      args:
        - BUFFER_OVERFLOW=1
        - BUFFER_SIZE=16  
    ports:
      - "14424:8080"
    restart: unless-stopped

  chatwithuser2:
    build:
      context: ./chatuser/
      dockerfile: ./macro_int/Dockerfile
      args:
        - INTEGER_OVERFLOW=1
        - BUFFER_SIZE=18  
    ports:
      - "14425:8080"
    restart: unless-stopped

